
# Use type function to see what type we are working with...
# Everything is a class or an object in python...
print(type(0))
print(type(" "))

# Use dir to get all the methods and special methods for a type...
print(dir({}))

# Use help to get information on how to use the methods...
print(help({}))
